### ISSUE TITLE
Messages for keywords not triggered

### ISSUE THREAD

**Issue by sellomkantjwa** [epoberezkin/ajv-errors#19] opened 2018-04-04 14:12 UTC
Hi,

I have a simple schema 
```
{
    "name": "getOrdersQuerySchema",
    "$id": "getOrdersQuerySchema",
    "type": "object",
    "properties": {
        "skip": {
            "type": "number",
            "minimum": 0
        },
        "sort": {
            "type": "string"
        },
        "recipient.reference": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "errorMessage": {
        "additionalProperties": "The allowed searchable fields are ...."
    }
}
```
When I validate this with an property not defined in the schema (e.g foo) I get the error `data/foo is an invalid additional property` 
I was expecting to see `The allowed searchable fields are ....`

Am I missing something? Interestingly if i do :

```
"errorMessage": "A generic error message."
```
Then it works.

**Comment by epoberezkin** [comment] 2018-04-04 14:24
Please submit a full working code sample, difficult to know what is the problem otherwise.

**Comment by sellomkantjwa** [comment] 2018-04-04 15:30
thanks @epoberezkin Here's a link to a minimal sample: https://runkit.com/sellomkantjwa/https-github-com-epoberezkin-ajv-errors-issues-19

**Comment by epoberezkin** [comment] 2018-04-04 15:53
It is almost a duplicate of #12 - the option errorDataPath is not supported by this package

**Closed** 2018-04-04 15:54 UTC
Labels: duplicate

**Comment by epoberezkin** [comment] 2018-04-04 15:56
See https://runkit.com/esp/5ac4f2ee17c55d00129c4a18 - it works without this option. It may be worth mentioning it in the docs, but please note that this option is now deprecated and can be removed.

**Comment by sellomkantjwa** [comment] 2018-04-05 09:15
Thanks @epoberezkin works like a charm.
